### PR TITLE
Add optee-os

### PR DESCRIPTION
**Pull request by iartemenko**
Deploy optee-os binaries only.

Signed-off-by: Iurii Artemenko <iurii_artemenko@epam.com>

### CODE REVIEW

**Comment by lorc** [comment]
Did you tried to built and flash OP-TEE provided by Linaro? Does  it work?

**Comment by iartemenko** [comment]
This one provided by Renesas, we "bbmask" OP-TEE provided by Linaro

**Comment by lorc** [comment]
Ah, I see. 

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by aanisov** [comment]
BTW, if we have BBMASK'ed optee, it would be better to remove that mask?

**Pull request closed without merging**
