### PR TITLE
Set proper branch of Xen for gen3-test product

### PR DESCRIPTION
**Pull request by iartemenko**
Signed-off-by: Iurii Artemenko <iurii_artemenko@epam.com>

### CODE REVIEW

**Comment by aanisov** [comment]
At least, explain how that branch fit the document.

**Comment by otyshchenko1** [comment]
@iartemenko pls change branch name to "RELEASE-4.10.0-xt0.2.gen3-test"

**Comment by aanisov** [comment]
I'm removing gen3-test

**Comment by iartemenko** [comment]
@otyshchenko1 Done

**Pull request merged**
