### PR TITLE
recipes-kernel: Remove unneeded patches from meta layer

### PR DESCRIPTION
**Pull request by otyshchenko1**
This must be in sync with migration to v4.14.75-ltsi/rcar-3.9.2.

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

Please see https://github.com/xen-troops/linux/pull/63

### CODE REVIEW

**Comment by andr2000** [comment]
USB 3 firmware is not needed anymore?

**Comment by otyshchenko1** [comment]
USB3 fw is needed, but meta-rcar-gen3 already does proper things. There is no need to make the same in extra meta-layer.

**Comment by andr2000** [comment]
`Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Comment by otyshchenko1** [comment]
There will be new PR which will contain this change...

**Pull request closed without merging**
